### ISSUE TITLE
Контакт

### ISSUE THREAD

**Issue by Sainero** [eddyem/stm32samples#1]
Здравствуйте, заинтриговал ваш ответ на https://www.cyberforum.ru/arm/thread3094714.html.
Не могли бы вы мне ответить на пару моментиков если не затруднит. Т.е. получается все параметры которые необходимо передавать, собирать и изменять будут находиться в EEPROM FLASH STM32 и их в любое время работы устройства, независимо от спящего режима ( в котором оно отмечено как опционально работает) можно будет изменить? Но как? Необходимо же для EEPROM прописать условия для терминала, т.е. ожидание команд (оформленных допустим в кейсах), правда не совсем понимаю как это будет пониматься в ПО. Получается написав приложение в visual studio, на стороне пользователя жмякается кнопка настройки параметра, а после выбора значения, отправляется например команда в hex формате, на которую МК отвечает изменением параметра работы устройства при этом не прерывая зашитый цикл работы?  Можете, пожалуйста отправить пример "У меня на всех железяках, требующих каких-то настроек, так и сделано." А то я уже потерялся в раздумьях, пересмотрев лекции и темы вашего сайта)

**Comment by eddyem** [comment]
У меня множество примеров есть под F0, F1 и F3. Понятно, что нельзя писать в одно и то же место, используется все свободное место и каждая следующая запись делается в следующую свободную область, как место кончается - вся флеш-память, используемая для хранения, стирается, и пишется заново. EEPROM у F-серий нет, поэтому и приходится ее эмулировать во флеше (а там уже не миллионы, а десятки - в худшем случае даже единицы - тысяч циклов перезаписи).
Например, здесь: https://github.com/eddyem/stm32samples/blob/master/F3:F303/Multistepper/flash.c
Настройки меняются "на лету", а если нужно их сохранить, я даю комаду 'saveconf', и МК сохраняет текущую структуру с настройками во флеш-памяти. Протокол у меня всегда текстовый: это очень удобно на стадии отладки, пока еще нет высокоуровневого ПО для работы с железякой. Да и + ко всему у меня есть сокет-сервер, позволяющий выполнять неблокирующий доступ из приличного количества приложений к одной железяке. Да даже просто посмотреть, что там происходит с потоком команд и ответов на них: открываю терминал (мой tty_term) на нужном порту и смотрю (можно вообще netcat использовать, но он, к сожалению, не разделяет ввод и вывод, да и не имеет истории команд).
