### ISSUE TITLE
Поддержка стандарта c99

### ISSUE THREAD

**Issue by Nikita-Presnov** [eddyem/stm32samples#2]
Возникли проблемы со стандартами си, ругается на u"COKPOWEHEU" и тому подобные контструкции
В мейкфайлах стандарт не зафиксирован, а между тем c99 применяетя сплошь и рядом.
Поддержка юникода появилась только с c11.

**Comment by eddyem** [comment]
А что за компилятор? gcc все это съедает без каких-либо флагов.
В интернетах пишут, что по умолчанию стандарт эквивалентен опции `-std=gnu17` - так что, без указания `-std` все должно нормально работать.
P.S. Я частенько применяю вещи из C11, но, как и писал, gcc это прекрасно съедает без упоминания `-std`
UPD:  [ссылка](https://stackoverflow.com/a/14737642/1965803)

**Comment by Nikita-Presnov** [comment]
Вот хочется как раз без фитч c11, у меня просто ряд прошивок завязаны именно на c99

**Comment by eddyem** [comment]
А какая разница? Пусть код будет C99, с опцией `-std=gnu23` он тоже соберется.

**Comment by Nikita-Presnov** [comment]
Не всегда, c99 прощал очень многое, а стандарт становится всё строже 
Ну да ладно, можно на int16 переписать потом
